CREATE ROLE `Admin`;
GRANT CREATE, SELECT, INSERT, UPDATE, DELETE ON Mindful_Study.* TO `Admin` WITH GRANT OPTION;

CREATE USER `Ching`@`%` IDENTIFIED BY 'PASSWORD';
GRANT `Admin` TO `Ching`@`%`;

CREATE USER `Theara`@`%` IDENTIFIED BY 'PASSWORD';
GRANT `Admin` TO `Theara`@`%`;

CREATE ROLE `User`;
GRANT SELECT, INSERT, UPDATE, DELETE ON Mindful_Study.* TO `User`;